//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the object_detection package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __object_detection__OBJECT_DETECTION_PIPELINE_CPPCONFIG_H__
#define __object_detection__OBJECT_DETECTION_PIPELINE_CPPCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace object_detection
{
  class object_detection_pipeline_cppConfigStatics;

  class object_detection_pipeline_cppConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(object_detection_pipeline_cppConfig &config, const object_detection_pipeline_cppConfig &max, const object_detection_pipeline_cppConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const object_detection_pipeline_cppConfig &config1, const object_detection_pipeline_cppConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, object_detection_pipeline_cppConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const object_detection_pipeline_cppConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, object_detection_pipeline_cppConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const object_detection_pipeline_cppConfig &config) const = 0;
      virtual void getValue(const object_detection_pipeline_cppConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T object_detection_pipeline_cppConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (object_detection_pipeline_cppConfig::* field);

      virtual void clamp(object_detection_pipeline_cppConfig &config, const object_detection_pipeline_cppConfig &max, const object_detection_pipeline_cppConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const object_detection_pipeline_cppConfig &config1, const object_detection_pipeline_cppConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, object_detection_pipeline_cppConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const object_detection_pipeline_cppConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, object_detection_pipeline_cppConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const object_detection_pipeline_cppConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const object_detection_pipeline_cppConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, object_detection_pipeline_cppConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, object_detection_pipeline_cppConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<object_detection_pipeline_cppConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(object_detection_pipeline_cppConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("passthrough_filter_x_low"==(*_i)->name){passthrough_filter_x_low = boost::any_cast<double>(val);}
        if("passthrough_filter_x_high"==(*_i)->name){passthrough_filter_x_high = boost::any_cast<double>(val);}
        if("passthrough_filter_y_low"==(*_i)->name){passthrough_filter_y_low = boost::any_cast<double>(val);}
        if("passthrough_filter_y_high"==(*_i)->name){passthrough_filter_y_high = boost::any_cast<double>(val);}
        if("passthrough_filter_z_low"==(*_i)->name){passthrough_filter_z_low = boost::any_cast<double>(val);}
        if("passthrough_filter_z_high"==(*_i)->name){passthrough_filter_z_high = boost::any_cast<double>(val);}
        if("voxel_filter_downsampling_leaf"==(*_i)->name){voxel_filter_downsampling_leaf = boost::any_cast<double>(val);}
        if("statistical_outlier_removal_K"==(*_i)->name){statistical_outlier_removal_K = boost::any_cast<double>(val);}
        if("statistical_outlier_removal_deviation"==(*_i)->name){statistical_outlier_removal_deviation = boost::any_cast<double>(val);}
        if("ransac_plane_segmentation_deviation"==(*_i)->name){ransac_plane_segmentation_deviation = boost::any_cast<double>(val);}
        if("euclidean_clustering_tolerance"==(*_i)->name){euclidean_clustering_tolerance = boost::any_cast<double>(val);}
        if("euclidean_clustering_max"==(*_i)->name){euclidean_clustering_max = boost::any_cast<double>(val);}
        if("euclidean_clustering_min"==(*_i)->name){euclidean_clustering_min = boost::any_cast<double>(val);}
      }
    }

    double passthrough_filter_x_low;
double passthrough_filter_x_high;
double passthrough_filter_y_low;
double passthrough_filter_y_high;
double passthrough_filter_z_low;
double passthrough_filter_z_high;
double voxel_filter_downsampling_leaf;
double statistical_outlier_removal_K;
double statistical_outlier_removal_deviation;
double ransac_plane_segmentation_deviation;
double euclidean_clustering_tolerance;
double euclidean_clustering_max;
double euclidean_clustering_min;

    bool state;
    std::string name;

    
}groups;



//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double passthrough_filter_x_low;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double passthrough_filter_x_high;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double passthrough_filter_y_low;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double passthrough_filter_y_high;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double passthrough_filter_z_low;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double passthrough_filter_z_high;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double voxel_filter_downsampling_leaf;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double statistical_outlier_removal_K;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double statistical_outlier_removal_deviation;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double ransac_plane_segmentation_deviation;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double euclidean_clustering_tolerance;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double euclidean_clustering_max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double euclidean_clustering_min;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("object_detection_pipeline_cppConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const object_detection_pipeline_cppConfig &__max__ = __getMax__();
      const object_detection_pipeline_cppConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const object_detection_pipeline_cppConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const object_detection_pipeline_cppConfig &__getDefault__();
    static const object_detection_pipeline_cppConfig &__getMax__();
    static const object_detection_pipeline_cppConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const object_detection_pipeline_cppConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void object_detection_pipeline_cppConfig::ParamDescription<std::string>::clamp(object_detection_pipeline_cppConfig &config, const object_detection_pipeline_cppConfig &max, const object_detection_pipeline_cppConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class object_detection_pipeline_cppConfigStatics
  {
    friend class object_detection_pipeline_cppConfig;

    object_detection_pipeline_cppConfigStatics()
    {
object_detection_pipeline_cppConfig::GroupDescription<object_detection_pipeline_cppConfig::DEFAULT, object_detection_pipeline_cppConfig> Default("Default", "", 0, 0, true, &object_detection_pipeline_cppConfig::groups);
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.passthrough_filter_x_low = -50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.passthrough_filter_x_low = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.passthrough_filter_x_low = 50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_x_low", "double", 0, "passthrough_filter_x_low", "", &object_detection_pipeline_cppConfig::passthrough_filter_x_low)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_x_low", "double", 0, "passthrough_filter_x_low", "", &object_detection_pipeline_cppConfig::passthrough_filter_x_low)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.passthrough_filter_x_high = -50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.passthrough_filter_x_high = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.passthrough_filter_x_high = 50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_x_high", "double", 0, "passthrough_filter_x_high", "", &object_detection_pipeline_cppConfig::passthrough_filter_x_high)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_x_high", "double", 0, "passthrough_filter_x_high", "", &object_detection_pipeline_cppConfig::passthrough_filter_x_high)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.passthrough_filter_y_low = -50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.passthrough_filter_y_low = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.passthrough_filter_y_low = 50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_y_low", "double", 0, "passthrough_filter_y_low", "", &object_detection_pipeline_cppConfig::passthrough_filter_y_low)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_y_low", "double", 0, "passthrough_filter_y_low", "", &object_detection_pipeline_cppConfig::passthrough_filter_y_low)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.passthrough_filter_y_high = -50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.passthrough_filter_y_high = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.passthrough_filter_y_high = 50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_y_high", "double", 0, "passthrough_filter_y_high", "", &object_detection_pipeline_cppConfig::passthrough_filter_y_high)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_y_high", "double", 0, "passthrough_filter_y_high", "", &object_detection_pipeline_cppConfig::passthrough_filter_y_high)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.passthrough_filter_z_low = -50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.passthrough_filter_z_low = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.passthrough_filter_z_low = 50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_z_low", "double", 0, "passthrough_filter_z_low", "", &object_detection_pipeline_cppConfig::passthrough_filter_z_low)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_z_low", "double", 0, "passthrough_filter_z_low", "", &object_detection_pipeline_cppConfig::passthrough_filter_z_low)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.passthrough_filter_z_high = -50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.passthrough_filter_z_high = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.passthrough_filter_z_high = 50.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_z_high", "double", 0, "passthrough_filter_z_high", "", &object_detection_pipeline_cppConfig::passthrough_filter_z_high)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("passthrough_filter_z_high", "double", 0, "passthrough_filter_z_high", "", &object_detection_pipeline_cppConfig::passthrough_filter_z_high)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.voxel_filter_downsampling_leaf = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.voxel_filter_downsampling_leaf = 10000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.voxel_filter_downsampling_leaf = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("voxel_filter_downsampling_leaf", "double", 0, "voxel_filter_downsampling_leaf", "", &object_detection_pipeline_cppConfig::voxel_filter_downsampling_leaf)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("voxel_filter_downsampling_leaf", "double", 0, "voxel_filter_downsampling_leaf", "", &object_detection_pipeline_cppConfig::voxel_filter_downsampling_leaf)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.statistical_outlier_removal_K = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.statistical_outlier_removal_K = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.statistical_outlier_removal_K = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("statistical_outlier_removal_K", "double", 0, "statistical_outlier_removal", "", &object_detection_pipeline_cppConfig::statistical_outlier_removal_K)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("statistical_outlier_removal_K", "double", 0, "statistical_outlier_removal", "", &object_detection_pipeline_cppConfig::statistical_outlier_removal_K)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.statistical_outlier_removal_deviation = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.statistical_outlier_removal_deviation = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.statistical_outlier_removal_deviation = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("statistical_outlier_removal_deviation", "double", 0, "statistical_outlier_removal_deviation", "", &object_detection_pipeline_cppConfig::statistical_outlier_removal_deviation)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("statistical_outlier_removal_deviation", "double", 0, "statistical_outlier_removal_deviation", "", &object_detection_pipeline_cppConfig::statistical_outlier_removal_deviation)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ransac_plane_segmentation_deviation = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ransac_plane_segmentation_deviation = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ransac_plane_segmentation_deviation = 1000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("ransac_plane_segmentation_deviation", "double", 0, "statistical_outlier_removal_deviation", "", &object_detection_pipeline_cppConfig::ransac_plane_segmentation_deviation)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("ransac_plane_segmentation_deviation", "double", 0, "statistical_outlier_removal_deviation", "", &object_detection_pipeline_cppConfig::ransac_plane_segmentation_deviation)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.euclidean_clustering_tolerance = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.euclidean_clustering_tolerance = 10000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.euclidean_clustering_tolerance = 2.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("euclidean_clustering_tolerance", "double", 0, "euclidean_clustering_tolerance", "", &object_detection_pipeline_cppConfig::euclidean_clustering_tolerance)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("euclidean_clustering_tolerance", "double", 0, "euclidean_clustering_tolerance", "", &object_detection_pipeline_cppConfig::euclidean_clustering_tolerance)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.euclidean_clustering_max = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.euclidean_clustering_max = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.euclidean_clustering_max = 100000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("euclidean_clustering_max", "double", 0, "euclidean_clustering_max", "", &object_detection_pipeline_cppConfig::euclidean_clustering_max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("euclidean_clustering_max", "double", 0, "euclidean_clustering_max", "", &object_detection_pipeline_cppConfig::euclidean_clustering_max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.euclidean_clustering_min = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.euclidean_clustering_min = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.euclidean_clustering_min = 100000.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("euclidean_clustering_min", "double", 0, "euclidean_clustering_min", "", &object_detection_pipeline_cppConfig::euclidean_clustering_min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr(new object_detection_pipeline_cppConfig::ParamDescription<double>("euclidean_clustering_min", "double", 0, "euclidean_clustering_min", "", &object_detection_pipeline_cppConfig::euclidean_clustering_min)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(object_detection_pipeline_cppConfig::AbstractGroupDescriptionConstPtr(new object_detection_pipeline_cppConfig::GroupDescription<object_detection_pipeline_cppConfig::DEFAULT, object_detection_pipeline_cppConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<object_detection_pipeline_cppConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<object_detection_pipeline_cppConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    object_detection_pipeline_cppConfig __max__;
    object_detection_pipeline_cppConfig __min__;
    object_detection_pipeline_cppConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const object_detection_pipeline_cppConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static object_detection_pipeline_cppConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &object_detection_pipeline_cppConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const object_detection_pipeline_cppConfig &object_detection_pipeline_cppConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const object_detection_pipeline_cppConfig &object_detection_pipeline_cppConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const object_detection_pipeline_cppConfig &object_detection_pipeline_cppConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<object_detection_pipeline_cppConfig::AbstractParamDescriptionConstPtr> &object_detection_pipeline_cppConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<object_detection_pipeline_cppConfig::AbstractGroupDescriptionConstPtr> &object_detection_pipeline_cppConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const object_detection_pipeline_cppConfigStatics *object_detection_pipeline_cppConfig::__get_statics__()
  {
    const static object_detection_pipeline_cppConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = object_detection_pipeline_cppConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __OBJECT_DETECTION_PIPELINE_CPPRECONFIGURATOR_H__
